### PR TITLE
Update dependencies to latest versions

### PR DESCRIPTION
**Pull request by AdrianEddy**
This PR updates all dependencies to the latest versions, mainly `nalgebra` to `0.29`

### CODE REVIEW

**Comment by AdrianEddy** [comment]
hmm looks like the tests fail to build when using `cargo test --no-default-features`. 
Using just `cargo test` it seems to work fine though.

Could someone look into the traits issue? I'm not very familiar with `simba` and its traits

**Comment by jmagnuson** [comment]
Appending

```toml
features = ["libm-force"]
```

to  the`nalgebra` entry should fix the 

```
    = note: the following trait bounds were not satisfied:
            `f64: RealField`
            which is required by `Mahony<f64>: Ahrs<f64>`
```

error in CI.

I'm not too familiar with simba either, but from https://github.com/dimforge/simba/pull/10, sounds like there are some potential perf gains by not pulling in `libm` in a `no-std` scenario. But I don't currently have time to dive in to see if ahrs's use-case is compatible with that setup, and it looks like simba was [previously](https://github.com/dimforge/simba/blob/e80c3a73804032ab1206dc0628147afece851919/Cargo.toml#L19) pulling in `libm` already.

**Comment by AdrianEddy** [comment]
Ok so since the `libm` was already pulled in, do you think we can just add the `features = ["libm-force"]` here and merge it like that?

**Comment by jmagnuson** [comment]
Yep, I think that's reasonable.

**Comment by jmagnuson** [comment]
LGTM, thanks!

**Pull request merged**
